# Generated by Django 2.2.6 on 2019-10-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contador',
            name='reading',
        ),
        migrations.AddField(
            model_name='reading',
            name='contador',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='energia.contador'),
        ),
    ]
