# Generated by Django 2.2 on 2019-10-08 04:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('energia', '0002_auto_20191004_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contador',
            new_name='meter',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='contador',
            new_name='meter',
        ),
    ]
